// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm--hNhBR_OEaQH_lCdyNhDdOw4rRD4FY',
    appId: '1:342619514960:web:c36a0abcda8353cfba0955',
    messagingSenderId: '342619514960',
    projectId: 'fitlab-79e45',
    authDomain: 'fitlab-79e45.firebaseapp.com',
    storageBucket: 'fitlab-79e45.firebasestorage.app',
    measurementId: 'G-K5K940P05V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGmlrckvvaq6jv7eKxGXRmQ2LN4R-zy7M',
    appId: '1:342619514960:android:e34b8deb5f799b08ba0955',
    messagingSenderId: '342619514960',
    projectId: 'fitlab-79e45',
    storageBucket: 'fitlab-79e45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzg5qCPaL6hE0mHj4Nt7zG9iucSQ-uyeY',
    appId: '1:342619514960:ios:4f13d04cc88b14b7ba0955',
    messagingSenderId: '342619514960',
    projectId: 'fitlab-79e45',
    storageBucket: 'fitlab-79e45.firebasestorage.app',
    iosBundleId: 'com.example.fitlabMobile2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzg5qCPaL6hE0mHj4Nt7zG9iucSQ-uyeY',
    appId: '1:342619514960:ios:4f13d04cc88b14b7ba0955',
    messagingSenderId: '342619514960',
    projectId: 'fitlab-79e45',
    storageBucket: 'fitlab-79e45.firebasestorage.app',
    iosBundleId: 'com.example.fitlabMobile2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm--hNhBR_OEaQH_lCdyNhDdOw4rRD4FY',
    appId: '1:342619514960:web:0477a07eae45778eba0955',
    messagingSenderId: '342619514960',
    projectId: 'fitlab-79e45',
    authDomain: 'fitlab-79e45.firebaseapp.com',
    storageBucket: 'fitlab-79e45.firebasestorage.app',
    measurementId: 'G-L5RB0WGNYE',
  );
}
